#!/usr/bin/env python3
"""Plays lock events as sound: note -> pitch, instrument -> timbre, volume -> loudness. Also chimes
lesson feedback. Stand-in for the game's audio (or the demo audio itself).

Instruments are real recorded-sounding notes generated by ElevenLabs (tools/gen_audio.py ->
assets/samples/), repitched to each note. Missing samples fall back to the built-in numpy synthesis.

  python tools/synth.py --test       # DO THIS FIRST: plays every instrument once, then exits
  python tools/synth.py              # listens on UDP 5006 (instead of tools/listen.py)
  python tools/synth.py --no-samples # numpy synthesis only

Without --test this is a SERVER: it binds the port and then sits there, silent, until run.py sends it a
lock event. "Nothing is happening" is what it looks like when it is working. Leave it running in its own
terminal and start run.py in another one.
"""
import argparse
import json
import socket
import sys
import threading
import time
from pathlib import Path

import numpy as np
import sounddevice as sd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from outer_vision.audio import read_wav  # noqa: E402
from outer_vision.music import midi  # noqa: E402
from outer_vision.pitch import repitch  # noqa: E402

SR = 44100


def env(n, attack, decay):
    t = np.arange(n) / SR
    return np.minimum(1.0, t / max(attack, 1e-4)) * np.exp(-t / decay)


def voice(instrument: str, f: float, dur=1.2) -> np.ndarray:
    n = int(SR * dur)
    t = np.arange(n) / SR
    if instrument == "piano":
        w = sum(np.sin(2 * np.pi * f * k * t) / k ** 1.3 for k in range(1, 7)) * env(n, 0.005, 0.5)
    elif instrument == "marimba":
        w = (np.sin(2 * np.pi * f * t) + 0.3 * np.sin(2 * np.pi * f * 4 * t) * env(n, 0.001, 0.05)) * env(n, 0.002, 0.25)
    elif instrument == "flute":
        vib = 1 + 0.004 * np.sin(2 * np.pi * 5 * t)
        w = (np.sin(2 * np.pi * f * vib * t) + 0.15 * np.sin(4 * np.pi * f * t)
             + 0.03 * np.random.default_rng(0).normal(size=n)) * np.minimum(1, t / 0.06) * np.exp(-np.maximum(0, t - 0.5) / 0.15)
    elif instrument == "strings":
        w = sum(np.sin(2 * np.pi * f * k * t) / k for k in range(1, 12)) * 0.5 * np.minimum(1, t / 0.15) * np.exp(-np.maximum(0, t - 0.6) / 0.2)
    elif instrument == "bell":
        w = sum(a * np.sin(2 * np.pi * f * r * t) * np.exp(-t / d) for r, a, d in
                [(1, 1, 1.2), (2.76, 0.5, 0.6), (5.4, 0.3, 0.3), (8.9, 0.2, 0.15)])
    elif instrument == "drum":
        f0 = f / 2
        sweep = 2 * np.pi * np.cumsum(f0 * (1 + 2 * np.exp(-t / 0.03))) / SR
        w = np.sin(sweep) * env(n, 0.001, 0.18) + 0.3 * np.random.default_rng(1).normal(size=n) * env(n, 0.001, 0.03)
    else:  # synth: soft square
        w = sum(np.sin(2 * np.pi * f * k * t) / k for k in range(1, 10, 2)) * env(n, 0.01, 0.3)
    return (w / (np.abs(w).max() + 1e-9)).astype(np.float32)


class Mixer:
    def __init__(self):
        self.voices, self.lock = [], threading.Lock()
        self.stream = sd.OutputStream(samplerate=SR, channels=1, dtype="float32", callback=self.cb, blocksize=256)
        self.stream.start()

    def play(self, wave, gain):
        with self.lock:
            self.voices.append([wave * gain, 0])

    def cb(self, out, frames, t, status):
        buf = np.zeros(frames, np.float32)
        with self.lock:
            for v in self.voices:
                chunk = v[0][v[1]:v[1] + frames]
                buf[:len(chunk)] += chunk
                v[1] += frames
            self.voices = [v for v in self.voices if v[1] < len(v[0])]
        out[:, 0] = np.tanh(buf)   # soft clip when voices overlap


def hz(note):
    return 440.0 * 2 ** ((midi(note) - 69) / 12)


SAMPLE_DIR = Path(__file__).resolve().parents[1] / "assets/samples"
MIDDLE_C = 261.63


def load_samples(d=SAMPLE_DIR):
    """name -> (float32 samples, sample rate, measured f0). f0 falls back to middle C (what was asked for)."""
    meta = json.loads((d / "samples.json").read_text()) if (d / "samples.json").exists() else {}
    out = {}
    for wav in sorted(d.glob("*.wav")):
        x, sr = read_wav(wav)
        out[wav.stem] = (x.astype(np.float32) / 32768, sr, (meta.get(wav.stem) or {}).get("f0") or MIDDLE_C)
    return out


def sampled(sample, f):
    """Repitch a sample to f Hz at the mixer's rate."""
    x, sr, f0 = sample
    w = repitch(x, (f / f0) * (sr / SR))
    return (w / (np.abs(w).max() + 1e-9)).astype(np.float32)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=5006)
    ap.add_argument("--test", action="store_true")
    ap.add_argument("--no-samples", action="store_true")
    args = ap.parse_args()
    samples = {} if args.no_samples else load_samples()
    print(f"samples: {sorted(samples) or 'none (numpy synthesis)'}", flush=True)

    def make(inst, note):
        return sampled(samples[inst], hz(note)) if inst in samples else voice(inst, hz(note))

    try:
        mix = Mixer()
    except Exception as e:      # no output device, or it's in use
        sys.exit(f"no speaker: {e}\n"
                 "Check System Settings > Sound > Output, and that something else isn't holding the device.")
    if args.test:
        print("playing C4 E4 G4 on each instrument - you should HEAR this now", flush=True)
        for inst in ["piano", "marimba", "flute", "strings", "bell", "drum", "synth"]:
            print(inst, "sample" if inst in samples else "synth", flush=True)
            for n in ("C4", "E4", "G4"):
                mix.play(make(inst, n), 0.6)
                time.sleep(0.35)
            time.sleep(0.5)
        time.sleep(1)
        print("done. Heard nothing? Check the Mac's output device and volume: System Settings > Sound.",
              flush=True)
        return
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind(("0.0.0.0", args.port))
    print(f"synth listening on udp :{args.port}  --  ready, and SILENT until run.py plays a note.\n"
          f"  Leave this running. Start the instrument in another terminal, e.g.\n"
          f"      .venv/bin/python run.py --source synthetic --gaze synthetic --realtime\n"
          f"  To check the speaker right now instead, stop this (Ctrl-C) and run:\n"
          f"      .venv/bin/python tools/synth.py --test\n"
          f"  Each note that arrives prints a line below. Ctrl-C to stop.", flush=True)
    cache = {}
    while True:
        msg = json.loads(sock.recv(65536))
        if msg.get("type") != "lock":
            continue
        o = msg["object"]
        if not o.get("note"):
            continue
        key = (o["instrument"], o["note"])
        if key not in cache:
            cache[key] = make(o["instrument"], o["note"])
        vol = o.get("volume") or 1.0
        mix.play(cache[key], 0.5 * vol)
        fb = msg.get("lesson")
        if fb and fb.get("done"):
            if "fanfare" in samples:
                threading.Timer(0.5, mix.play, (sampled(samples["fanfare"], samples["fanfare"][2]), 0.4)).start()
            else:
                for i, n in enumerate(["C5", "E5", "G5", "C6"]):   # little fanfare
                    threading.Timer(0.5 + 0.12 * i, mix.play, (voice("bell", hz(n), 0.8), 0.3)).start()
        print(f"{o['note']:>4} {o['instrument']:<8} vol {vol:.2f}"
              + ("" if not fb else f"  lesson {fb['index']}/{fb['total']} {'✓' if fb['correct'] else '✗'}"), flush=True)


if __name__ == "__main__":
    main()
